spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

logging:
  level:
    root: DEBUG

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    mail:
      enabled: false
    redis:
      enabled: false
