ALTER TABLE GO_USER
    ADD COLUMN sign_up_id VARCHAR(36) UNIQUE;

ALTER TABLE GO_USER
    ADD CONSTRAINT fk_sign_up
        FOREIGN KEY (sign_up_id) REFERENCES GO_SIGN_UP(id)
            ON DELETE SET NULL;
